export const DATA_LOADING = "DATA_LOADING";
export const DATA_LOAD_SUCCESS = "DATA_LOAD_SUCCESS";
export const DATA_LOAD_FAIL = "DATA_LOAD_FAIL";

export const COUNTRIES_LOADING = "COUNTRIES_LOADING";
export const COUNTRIES_LOAD_SUCCESS = "COUNTRIES_LOAD_SUCCESS";
export const COUNTRIES_LOAD_FAIL = "COUNTRIES_LOAD_FAIL";
